name: Jest Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub's Linux VM

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20  # LTS version

      # 3. Install dependencies
      - run: yarn install --frozen-lockfile

      # 4. Run Jest tests
      - run: yarn test